# Generated by Django 5.1.2 on 2025-11-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_doctor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
